dataset_root: "/mnt/ml-data-storage/jens/zodmini"  # point this to the root folder of the zod dataset you are using
# dataset_root: "/mnt/ml-data-storage/jens/zodmini" # point this to the root folder of the zod dataset you are using
dataset_export_dir: "../data/zodmini"
dataset_version: "mini" # mini or full
dataset_name: "zodmini" # you can change this to anything you would like
dataset_persistent: True # if true, dataset will be saved locally for later use
filename_URL_encoding: False # Might need to be set to true on Windows systems